### ISSUE TITLE
Cannot parse resign

### ISSUE THREAD

**Issue by Dorus** [fsparv/LeelaWatcher#14] opened 2017-12-08 20:02 UTC
see https://github.com/gcp/leela-zero/issues/306

Resignation was recently turned on and LeelaWatcher crashes on it.

**Comment by FelixBrendel** [comment] 2017-12-08 20:42
Are you using the latest release? 
![image](https://user-images.githubusercontent.com/5005975/33784296-a1d73dbe-dc60-11e7-9d76-e06942ad8032.png)
The latest version of LeelaWatcher should parse the resignation.

**Comment by fsparv** [comment] 2017-12-11 05:50
Duplicate of #13

**Closed as completed by fsparv** 2017-12-11 05:50 UTC
