### ISSUE TITLE
run with autogtp 11?

### ISSUE THREAD

**Issue by ThorAvaTahr** [fsparv/LeelaWatcher#21] opened 2018-01-07 21:52 UTC
I can run autogtp 11 with leelawatcher, but the moves don't show, same  as #19 

BTW this works: C:\Users\...\Downloads\LeelaZero>java -jar ../LeelaWatcher-1.0.2.jar . autogtp.exe , but somehow this fails, why?

**C:\Users\...\Downloads>java -jar LeelaWatcher-1.0.2.jar C:\Users\...\Downl
oads\leelazero autogtp.exe**

java.io.IOException: Cannot run program "autogtp.exe" (in directory "C:\Users\...\Downloads\leelazero"): CreateProcess error=2, The system cannot find the fi
le specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at leelawatcher.gui.LeelaWatcher.lambda$main$1(LeelaWatcher.java:70)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find th
e file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 16 more

**Comment by fsparv** [comment] 2018-01-08 06:42
This appears to be two issues: 
-  a duplicate of #19, since #19's "next branch" probably became autogtp 11.
- a question about different modes of specifying the directory. 

In the future please always file separate issues as separate tickets. The duplicate should be closed and I would like to explore the question, but now it's going to be a discussion about file paths under a title about autogtp 11...

The first argument tells the program what directory should be the working directory for the process it spawns, and the second is the command to run. I'm not entirely sure how this might interact with the windows cmd shell, can you try quoting the values, and check that none of the values have spaces like "C:\User\Thor son of Odin\Downloads\" 

That said, I realize that it's not entirely clear if "working directory for the spawned process" (as documented by oracle) actually implies name resolution from that directory for the name of the executable, or merely that after resolution, the process is started working in that directory. Therefore it would be interesting to try:

java -jar LeelaWatcher-1.0.2.jar C:\Users...\Downloads\LeelaZero LeelaZero\autogtp.exe

Might work, which would be an irritating result, but perhaps not entirely inconsistent with oracle's vague wording. I don't have a windows test environment, so I can't directly validate this without taking time to setup on windows (presently I'm buried in paid work).

**Comment by barrybecker4** [comment] 2018-01-21 15:31
I had noticed the similar behavior on windows from a git bash window.
This is what worked for me:

`java -jar e:/projects/LeelaWatcher/build/libs/LeelaWatcher-1.0.2.jar . autogtp.exe`

Doing
`java -jar LeelaWatcher-1.0.2.jar e:/apps/leela-zero-11 autogtp.exe`

did not work as the domumentation suggested.
The error was: 
`IOException: Cannot run program "autogtp.exe" (in directory "e:\apps\leela-zero-11"): CreateProcess error=2, The system cannot find the file specified
`
I think the problem might be that it needs to access other exe's like curl in that directory, so you need to run it from the directory that has autogtp, curl and other exes.

**Comment by fsparv** [comment] 2018-01-29 02:09
fixed in release 1.1.0

**Closed as completed by fsparv** 2018-01-29 02:09 UTC
