### ISSUE TITLE
support for the next branch?

### ISSUE THREAD

**Issue by alreadydone** [fsparv/LeelaWatcher#19] opened 2017-12-26 19:05 UTC
Although LeelaWatcher can run with autogtp_next, no stones are displayed on the board as moves are generated.

**Comment by alreadydone** [comment] 2017-12-26 19:11
looks like the next branch changed the output format so one needs to change the pattern matchings in AutoGtpOutputParser.java ...

**Comment by barrybecker4** [comment] 2018-01-21 15:24
Yes, I am seeing this when using autogtp 11 too. I'll have a look at fixing AutoGtpOutputParser if I can figure out how things changed.

**Comment by barrybecker4** [comment] 2018-01-21 16:58
I think I found the change in the leela-zero source that broke LeelaWatcher.
On 12/9 Marco Calignana made a change to autogtp/Game.cpp to improve the move output.
Instead of writing "<movenum> (<moveCoords>)" for each move, it now writes
"<movenum> (<color> <moveCoords)" for each move.
If I fix this, I assume that we need to bump the version and then say something like 1.0.3 will only work for leela-zero gtp version 11.0 and above, while 1.0.2 is for previous versions.

**Comment by barrybecker4** [comment] 2018-01-21 17:32
Oh never mind, I see that there is already an outstanding pull request for this problem submitted 9 days ago. Hope it can be merged soon.

**Comment by fsparv** [comment] 2018-01-21 22:31
Will try to get to it soon, sorry for the delay I was on vacation, and of course work piles up before and after vacation...

**Comment by barrybecker4** [comment] 2018-01-26 18:21
This is also a dupe of #19.

**Comment by fsparv** [comment] 2018-01-29 02:08
fixed in release 1.1.0

**Closed as completed by fsparv** 2018-01-29 02:08 UTC
Labels: enhancement
